Repository deborah620/ITSME, pull requests merged in 2022-04, with the labels that each got.

#31 Survey post api
  itsmeapp/urls.py
  itsmeapp/views.py
Labels: story

#28 Taylor branch
  .idea/.gitignore
  .idea/ITSME.iml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  itsme/__init__.py
  itsme/asgi.py
  itsme/settings.py
  itsme/urls.py
  itsme/wsgi.py
  itsmeapp/__init__.py
  itsmeapp/admin.py
  itsmeapp/apps.py
  itsmeapp/migrations/__init__.py
  itsmeapp/models.py
  itsmeapp/static/css/all.css
  itsmeapp/templates/itsmeapp/index.html
  itsmeapp/tests.py
  itsmeapp/urls.py
  itsmeapp/views.py
  manage.py
  requirements.txt
Labels: functionality, front end

#33 added comments
  itsmeapp/templates/itsmeapp/index.html
Labels: functionality, front end

#34 Front end merge to develop
  itsmeapp/templates/itsmeapp/index.html
Labels: functionality, front end

#38 Download results
  itsmeapp/migrations/0001_initial.py
  itsmeapp/templates/itsmeapp/index.html
  itsmeapp/tests.py
  itsmeapp/urls.py
  itsmeapp/views.py
  results.csv
Labels: back end
